# Generated by Django 6.0.2 on 2026-02-20 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='total_violations',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='result',
            name='violations_copy_paste',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='result',
            name='violations_focus_lost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='result',
            name='violations_json',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='result',
            name='violations_right_click',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='result',
            name='violations_screenshot',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='result',
            name='violations_tab_switch',
            field=models.IntegerField(default=0),
        ),
    ]
